name: Deploy to S3

on:
  push:
    branches:
      - main  # Production branch
      - staging  # Staging branch

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --f

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET_STAGING }}
          fi

          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESSKEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY_ACCESS }}
          export AWS_DEFAULT_REGION=us-east-1
          aws s3 sync build s3://$AWS_S3_BUCKET

      - name: Invalidate CloudFront cache
        run: |
          echo "Starting CloudFront invalidation"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            export CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            export CLOUDFRONT_DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          fi

          export AWS_DEFAULT_REGION=us-east-1
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
          echo "Invalidation completed"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ACCESS }}
